<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->title)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('node', substr($_SERVER['SERVER_ADDR'], 8) )
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->headLink(['rel' => 'apple-touch-icon', 'href' => $this->basePath() . '/img/apple-touch-icon.png'])
            ->prependStylesheet($this->basePath('css/style.css'), 'screen,print')
            ->prependStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', 'screen,print')
            ->prependStylesheet('https://use.fontawesome.com/releases/v5.7.2/css/all.css', 'screen,print')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js')
            ->prependFile('https://code.jquery.com/jquery-3.3.1.slim.min.js')
        ?>
    </head>
    <body>
    	<?= $this->content ?>
        <?= $this->inlineScript() ?>
    </body>
</html>